INSERT INTO estados VALUES (1, 'Michoacán de Ocampo');
INSERT INTO municipios VALUES (1, 'Cuitzeo', 1);
INSERT INTO municipios VALUES (2, 'Municipios', 1);
INSERT INTO municipios VALUES (3, 'Angangueo', 1);
INSERT INTO municipios VALUES (4, 'Lagunillas', 1);
INSERT INTO municipios VALUES (5, 'Ocampo', 1);
INSERT INTO municipios VALUES (6, 'Tzintzuntzan', 1);
INSERT INTO municipios VALUES (7, 'Tlazazalca', 1);
INSERT INTO municipios VALUES (8, 'Arteaga', 1);
INSERT INTO municipios VALUES (9, 'Copándaro', 1);
INSERT INTO municipios VALUES (10, 'Gabriel Zamora', 1);
INSERT INTO municipios VALUES (11, 'Tangancícuaro', 1);
INSERT INTO municipios VALUES (12, 'Venustiano Carranza', 1);
INSERT INTO municipios VALUES (13, 'Cojumatlán de Régules', 1);
INSERT INTO municipios VALUES (14, 'Nuevo Parangaricutiro', 1);
INSERT INTO municipios VALUES (15, 'Panindícuaro', 1);
INSERT INTO municipios VALUES (16, 'Huetamo', 1);
INSERT INTO municipios VALUES (17, 'Purépero', 1);
INSERT INTO municipios VALUES (18, 'Tuxpan', 1);
INSERT INTO municipios VALUES (19, 'Cherán', 1);
INSERT INTO municipios VALUES (20, 'Coeneo', 1);
INSERT INTO municipios VALUES (21, 'Uruapan', 1);
INSERT INTO municipios VALUES (22, 'Salvador Escalante', 1);
INSERT INTO municipios VALUES (23, 'Penjamillo', 1);
INSERT INTO municipios VALUES (24, 'José Sixto Verduzco', 1);
INSERT INTO municipios VALUES (25, 'Tuzantla', 1);
INSERT INTO municipios VALUES (26, 'Tarímbaro', 1);
INSERT INTO municipios VALUES (27, 'Parácuaro', 1);
INSERT INTO municipios VALUES (28, 'Álvaro Obregón', 1);
INSERT INTO municipios VALUES (29, 'Charapan', 1);
INSERT INTO municipios VALUES (30, 'Tumbiscatío', 1);
INSERT INTO municipios VALUES (31, 'Aguililla', 1);
INSERT INTO municipios VALUES (32, 'Sahuayo', 1);
INSERT INTO municipios VALUES (33, 'Morelia', 1);
INSERT INTO colonias VALUES (1, 'Aracurio', 'null', 33);
INSERT INTO colonias VALUES (2, 'Campichahua', 'null', 33);
INSERT INTO colonias VALUES (3, 'Cuanajillo del Toro', 'null', 33);
INSERT INTO colonias VALUES (4, 'Curimeo', 'null', 33);
INSERT INTO colonias VALUES (5, 'Parritas', 'null', 33);
INSERT INTO colonias VALUES (6, 'Puentecillas (Puentecitas)', 'null', 33);
INSERT INTO colonias VALUES (7, 'La Soledad', 'null', 33);
INSERT INTO colonias VALUES (8, 'Puente Hernández', 'null', 33);
INSERT INTO colonias VALUES (9, 'El Carretero', 'null', 33);
INSERT INTO colonias VALUES (10, 'La Laguna (Los Caracoles)', 'null', 33);
INSERT INTO colonias VALUES (11, 'Cañada de Buena Vista', 'null', 33);
INSERT INTO colonias VALUES (12, 'La Codorniz', 'null', 33);
INSERT INTO colonias VALUES (13, 'Patambo', 'null', 33);
INSERT INTO colonias VALUES (14, 'Los Capulines', 'null', 33);
INSERT INTO colonias VALUES (15, 'Las Mesitas', 'null', 33);
INSERT INTO colonias VALUES (16, 'Colonia Abel Martínez', 'null', 33);
INSERT INTO colonias VALUES (17, 'Las Guares', 'null', 33);
INSERT INTO colonias VALUES (18, 'Fraccionamiento la Purísima', 'null', 33);
INSERT INTO colonias VALUES (19, 'Colonia Ejidal Lomas de Guadalupe', 'null', 33);
INSERT INTO colonias VALUES (20, 'Joyitas del Cuetazo', 'null', 33);
INSERT INTO colonias VALUES (21, 'La Mora', 'null', 33);
INSERT INTO colonias VALUES (22, 'El Barretero Tercera Etapa', 'null', 33);
INSERT INTO colonias VALUES (23, 'Manantiales del Parián', 'null', 33);
INSERT INTO colonias VALUES (24, 'La Herradura (Antiguo Camino Real)', 'null', 33);
INSERT INTO colonias VALUES (25, 'La Alberca', 'null', 33);
INSERT INTO colonias VALUES (26, 'Arroyo Colorado', 'null', 33);
INSERT INTO colonias VALUES (27, 'Asiento de Piedra (El Chirihuindo)', 'null', 33);
INSERT INTO colonias VALUES (28, 'Atécuaro', 'null', 33);
INSERT INTO colonias VALUES (29, 'El Bañito', 'null', 33);
INSERT INTO colonias VALUES (30, 'Buenavista', 'null', 33);
INSERT INTO colonias VALUES (31, 'Buenavista', 'null', 33);
INSERT INTO colonias VALUES (32, 'Buenavista', 'null', 33);
INSERT INTO colonias VALUES (33, 'Capula', 'null', 33);
INSERT INTO colonias VALUES (34, 'Puerto del Madroño', 'null', 33);
INSERT INTO colonias VALUES (35, 'Cerritos', 'null', 33);
INSERT INTO colonias VALUES (36, 'La Cofradía', 'null', 33);
INSERT INTO colonias VALUES (37, 'Coro Grande', 'null', 33);
INSERT INTO colonias VALUES (38, 'El Correo', 'null', 33);
INSERT INTO colonias VALUES (39, 'Cotzurio', 'null', 33);
INSERT INTO colonias VALUES (40, 'Las Cruces', 'null', 33);
INSERT INTO colonias VALUES (41, 'Cuanajillo Grande', 'null', 33);
INSERT INTO colonias VALUES (42, 'Los Cuervos', 'null', 33);
INSERT INTO colonias VALUES (43, 'Chihuerio', 'null', 33);
INSERT INTO colonias VALUES (44, 'Chiquimitío', 'null', 33);
INSERT INTO colonias VALUES (45, 'El Durazno', 'null', 33);
INSERT INTO colonias VALUES (46, 'El Escobal', 'null', 33);
INSERT INTO colonias VALUES (47, 'Las Flores', 'null', 33);
INSERT INTO colonias VALUES (48, 'El Fresno', 'null', 33);
INSERT INTO colonias VALUES (49, 'Hojas Anchas', 'null', 33);
INSERT INTO colonias VALUES (50, 'Huertitas', 'null', 33);
INSERT INTO colonias VALUES (51, 'Ichaqueo', 'null', 33);
INSERT INTO colonias VALUES (52, 'Iratzio', 'null', 33);
INSERT INTO colonias VALUES (53, 'Jerécuaro', 'null', 33);
INSERT INTO colonias VALUES (54, 'Joya de Buenavista', 'null', 33);
INSERT INTO colonias VALUES (55, 'Joya de la Huerta', 'null', 33);
INSERT INTO colonias VALUES (56, 'Joyitas', 'null', 33);
INSERT INTO colonias VALUES (57, 'Los Laureles (Ejido Los Laureles)', 'null', 33);
INSERT INTO colonias VALUES (58, 'Loma Caliente', 'null', 33);
INSERT INTO colonias VALUES (59, 'Loma Puerto del Tigre (Loma del Tigre)', 'null', 33);
INSERT INTO colonias VALUES (60, 'La Maiza', 'null', 33);
INSERT INTO colonias VALUES (61, 'Nieves', 'null', 33);
INSERT INTO colonias VALUES (62, 'Nueva Florida', 'null', 33);
INSERT INTO colonias VALUES (63, 'Ojo de Agua', 'null', 33);
INSERT INTO colonias VALUES (64, 'La Artesa', 'null', 33);
INSERT INTO colonias VALUES (65, 'Las Palomas', 'null', 33);
INSERT INTO colonias VALUES (66, 'El Pino (El Pino Cuate)', 'null', 33);
INSERT INTO colonias VALUES (67, 'El Porvenir (Rancho de Jesús)', 'null', 33);
INSERT INTO colonias VALUES (68, 'Potrerillos', 'null', 33);
INSERT INTO colonias VALUES (69, 'La Presa (La Presa de Chiquimitío)', 'null', 33);
INSERT INTO colonias VALUES (70, 'Pueblo Viejo', 'null', 33);
INSERT INTO colonias VALUES (71, 'Pueblo Viejo', 'null', 33);
INSERT INTO colonias VALUES (72, 'Estación Jácuaro (Colonia la Reunión)', 'null', 33);
INSERT INTO colonias VALUES (73, 'Río Bello (El Campamento)', 'null', 33);
INSERT INTO colonias VALUES (74, 'San Antonio Carupo', 'null', 33);
INSERT INTO colonias VALUES (75, 'San Antonio Coapa', 'null', 33);
INSERT INTO colonias VALUES (76, 'San Antonio Parangare', 'null', 33);
INSERT INTO colonias VALUES (77, 'San Bernabé', 'null', 33);
INSERT INTO colonias VALUES (78, 'San Carlos Coapa', 'null', 33);
INSERT INTO colonias VALUES (79, 'San José Coapa', 'null', 33);
INSERT INTO colonias VALUES (80, 'San José de las Torres', 'null', 33);
INSERT INTO colonias VALUES (81, 'San Miguel Coapa', 'null', 33);
INSERT INTO colonias VALUES (82, 'San Miguel del Monte', 'null', 33);
INSERT INTO colonias VALUES (83, 'San Nicolás Obispo', 'null', 33);
INSERT INTO colonias VALUES (84, 'San Pedro Chicácuaro', 'null', 33);
INSERT INTO colonias VALUES (85, 'San Rafael Coapa', 'null', 33);
INSERT INTO colonias VALUES (86, 'Zimpanio Sur', 'null', 33);
INSERT INTO colonias VALUES (87, 'Tacícuaro', 'null', 33);
INSERT INTO colonias VALUES (88, 'El Taray', 'null', 33);
INSERT INTO colonias VALUES (89, 'Tarehuicho', 'null', 33);
INSERT INTO colonias VALUES (90, 'Teremendo de los Reyes', 'null', 33);
INSERT INTO colonias VALUES (91, 'Teremendo Jasso', 'null', 33);
INSERT INTO colonias VALUES (92, 'Tirio', 'null', 33);
INSERT INTO colonias VALUES (93, 'Tiristarán', 'null', 33);
INSERT INTO colonias VALUES (94, 'Torrecillas (La Torrecilla)', 'null', 33);
INSERT INTO colonias VALUES (95, 'Las Trojes', 'null', 33);
INSERT INTO colonias VALUES (96, 'Tumbisca', 'null', 33);
INSERT INTO colonias VALUES (97, 'La Tuna Manza', 'null', 33);
INSERT INTO colonias VALUES (98, 'Tzintzimacato Chico', 'null', 33);
INSERT INTO colonias VALUES (99, 'Tzintzimacato Grande', 'null', 33);
INSERT INTO colonias VALUES (100, 'Umécuaro', 'null', 33);
INSERT INTO colonias VALUES (101, 'Uruapilla', 'null', 33);
INSERT INTO colonias VALUES (102, 'La Yerbabuena', 'null', 33);
INSERT INTO colonias VALUES (103, 'Zajo Chico', 'null', 33);
INSERT INTO colonias VALUES (104, 'Zajo Grande', 'null', 33);
INSERT INTO colonias VALUES (105, 'La Cieneguita (La Ciénega)', 'null', 33);
INSERT INTO colonias VALUES (106, 'La Ceja', 'null', 33);
INSERT INTO colonias VALUES (107, 'La Palmita (La Trampa)', 'null', 33);
INSERT INTO colonias VALUES (108, 'Torrecillas', 'null', 33);
INSERT INTO colonias VALUES (109, 'El Agua Escondida', 'null', 33);
INSERT INTO colonias VALUES (110, 'La Mintzita (Piedra Dura)', 'null', 33);
INSERT INTO colonias VALUES (111, 'El Laurelito (La Izama)', 'null', 33);
INSERT INTO colonias VALUES (112, 'La Ciénega (Torrecillas de Atécuaro)', 'null', 33);
INSERT INTO colonias VALUES (113, 'San Rafaelillo (La Haciendita)', 'null', 33);
INSERT INTO colonias VALUES (114, 'Ojo de Agua (Escorpión Potrerito)', 'null', 33);
INSERT INTO colonias VALUES (115, 'El Arenal', 'null', 33);
INSERT INTO colonias VALUES (116, 'El Mesón Colorado', 'null', 33);
INSERT INTO colonias VALUES (117, 'La Hacienda de Atapaneo', 'null', 33);
INSERT INTO colonias VALUES (118, 'La Ciénega (La Calera)', 'null', 33);
INSERT INTO colonias VALUES (119, 'Don Chema Mondragón', 'null', 33);
INSERT INTO colonias VALUES (120, 'Colonia Valle Ejidal', 'null', 33);
INSERT INTO colonias VALUES (121, 'La Morita (Colonia la Morita)', 'null', 33);
INSERT INTO colonias VALUES (122, 'Colonia Ampliación de San Isidro Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (123, 'Colonia Guadalupe Victoria', 'null', 33);
INSERT INTO colonias VALUES (124, 'Colonia Valle del Real', 'null', 33);
INSERT INTO colonias VALUES (125, 'Mirador de Morelia', 'null', 33);
INSERT INTO colonias VALUES (126, 'Colonia Mujeres Mexicanas', 'null', 33);
INSERT INTO colonias VALUES (127, 'Colonia Luis Donaldo Colosio', 'null', 33);
INSERT INTO colonias VALUES (128, 'El Rodeo (Las Praderas)', 'null', 33);
INSERT INTO colonias VALUES (129, 'La Nopalera', 'null', 33);
INSERT INTO colonias VALUES (130, 'Colonia 10 de Junio', 'null', 33);
INSERT INTO colonias VALUES (131, 'La Providencia', 'null', 33);
INSERT INTO colonias VALUES (132, 'Palo Amarillo', 'null', 33);
INSERT INTO colonias VALUES (133, 'Fraccionamiento Santa Inés', 'null', 33);
INSERT INTO colonias VALUES (134, 'Colonia Nuevo Horizonte', 'null', 33);
INSERT INTO colonias VALUES (135, 'Ampliación Capula', 'null', 33);
INSERT INTO colonias VALUES (136, 'Colonia 13 de Abril', 'null', 33);
INSERT INTO colonias VALUES (137, 'Colonia los Gigantes', 'null', 33);
INSERT INTO colonias VALUES (138, 'La Manga', 'null', 33);
INSERT INTO colonias VALUES (139, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (140, 'Colonia el Ciprés', 'null', 33);
INSERT INTO colonias VALUES (141, 'Vista Hermosa', 'null', 33);
INSERT INTO colonias VALUES (142, 'Ampliación la Aldea', 'null', 33);
INSERT INTO colonias VALUES (143, 'Colonia la Ermita', 'null', 33);
INSERT INTO colonias VALUES (144, 'Colonia Margarita Morán', 'null', 33);
INSERT INTO colonias VALUES (145, 'La Mesa [Quinta Club]', 'null', 33);
INSERT INTO colonias VALUES (146, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (147, 'La Nueva Aldea (Villas Oriente) [Fraccionamiento]', 'null', 33);
INSERT INTO colonias VALUES (148, 'El Tejocote (La Cortina)', 'null', 33);
INSERT INTO colonias VALUES (149, 'San Agustín', 'null', 33);
INSERT INTO colonias VALUES (150, 'El Aguaje', 'null', 33);
INSERT INTO colonias VALUES (151, 'Manga Prieta', 'null', 33);
INSERT INTO colonias VALUES (152, 'Colonia Bella Vista', 'null', 33);
INSERT INTO colonias VALUES (153, 'Colonia José Vasconcelos', 'null', 33);
INSERT INTO colonias VALUES (154, 'Gaviotas de Quinceo', 'null', 33);
INSERT INTO colonias VALUES (155, 'Morelia', 'null', 33);
INSERT INTO colonias VALUES (156, 'La Aldea', 'null', 33);
INSERT INTO colonias VALUES (157, 'Hacienda de Aparangueo', 'null', 33);
INSERT INTO colonias VALUES (158, 'Atapaneo', 'null', 33);
INSERT INTO colonias VALUES (159, 'Buenos Aires', 'null', 33);
INSERT INTO colonias VALUES (160, 'La Carbonera', 'null', 33);
INSERT INTO colonias VALUES (161, 'Coíntzio', 'null', 33);
INSERT INTO colonias VALUES (162, 'La Concepción', 'null', 33);
INSERT INTO colonias VALUES (163, 'Cuto de la Esperanza', 'null', 33);
INSERT INTO colonias VALUES (164, 'Emiliano Zapata', 'null', 33);
INSERT INTO colonias VALUES (165, 'La Estancia', 'null', 33);
INSERT INTO colonias VALUES (166, 'Isaac Arriaga (Noriega)', 'null', 33);
INSERT INTO colonias VALUES (167, 'Jesús del Monte (La Capilla)', 'null', 33);
INSERT INTO colonias VALUES (168, 'La Luz', 'null', 33);
INSERT INTO colonias VALUES (169, 'Morelos', 'null', 33);
INSERT INTO colonias VALUES (170, 'Pío (Hacienda del Pío)', 'null', 33);
INSERT INTO colonias VALUES (171, 'Los Pirules (La Estancia)', 'null', 33);
INSERT INTO colonias VALUES (172, 'Puerta del Varal', 'null', 33);
INSERT INTO colonias VALUES (173, 'Puerto de Buenavista (Lázaro Cárdenas)', 'null', 33);
INSERT INTO colonias VALUES (174, 'Rancho Viejo', 'null', 33);
INSERT INTO colonias VALUES (175, 'El Reparo', 'null', 33);
INSERT INTO colonias VALUES (176, 'El Resumidero', 'null', 33);
INSERT INTO colonias VALUES (177, 'Francisco J. Múgica', 'null', 33);
INSERT INTO colonias VALUES (178, 'San Isidro Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (179, 'San José Itzícuaro (Rancho Nuevo)', 'null', 33);
INSERT INTO colonias VALUES (180, 'San Juanito Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (181, 'San Lorenzo Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (182, 'Santa Rosalía', 'null', 33);
INSERT INTO colonias VALUES (183, 'Santiago Undameo', 'null', 33);
INSERT INTO colonias VALUES (184, 'Las Tinajas (La Tinaja)', 'null', 33);
INSERT INTO colonias VALUES (185, 'Tiripetío', 'null', 33);
INSERT INTO colonias VALUES (186, 'Chumbiricua (Ojo de Agua)', 'null', 33);
INSERT INTO colonias VALUES (187, 'El Landín', 'null', 33);
INSERT INTO colonias VALUES (188, 'Puente Gallegos', 'null', 33);
INSERT INTO colonias VALUES (189, 'Puerta Blanca', 'null', 33);
INSERT INTO colonias VALUES (190, 'La Corucha', 'null', 33);
INSERT INTO colonias VALUES (191, 'El Salto', 'null', 33);
INSERT INTO colonias VALUES (192, 'La Sanguijuela', 'null', 33);
INSERT INTO colonias VALUES (193, 'Parastaco', 'null', 33);
INSERT INTO colonias VALUES (194, 'Puerto de Celaya', 'null', 33);
INSERT INTO colonias VALUES (195, 'Puerto la Sosa', 'null', 33);
INSERT INTO colonias VALUES (196, 'El Cerrito Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (197, 'La Puente', 'null', 33);
INSERT INTO colonias VALUES (198, 'Santa Mónica', 'null', 33);
INSERT INTO colonias VALUES (199, 'La Mina', 'null', 33);
INSERT INTO colonias VALUES (200, 'Agua Zarca', 'null', 33);
INSERT INTO colonias VALUES (201, 'El Alacrán', 'null', 33);
INSERT INTO colonias VALUES (202, 'CRISOBA Industrial (CEPAMISA)', 'null', 33);
INSERT INTO colonias VALUES (203, 'El Tremecino', 'null', 33);
INSERT INTO colonias VALUES (204, 'Biricuaran', 'null', 33);
INSERT INTO colonias VALUES (205, 'Campo de Tiro', 'null', 33);
INSERT INTO colonias VALUES (206, 'Lomas de la Maestranza', 'null', 33);
INSERT INTO colonias VALUES (207, 'Las Garzas (Privada del Bosque)', 'null', 33);
INSERT INTO colonias VALUES (208, 'Hermenegildo Galeana', 'null', 33);
INSERT INTO colonias VALUES (209, 'Fraccionamiento Huertos Agua Azul', 'null', 33);
INSERT INTO colonias VALUES (210, 'Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (211, 'El Jazmín', 'null', 33);
INSERT INTO colonias VALUES (212, 'El Ranchito', 'null', 33);
INSERT INTO colonias VALUES (213, 'Colonia la Palma', 'null', 33);
INSERT INTO colonias VALUES (214, 'La Planta [Termoeléctrica]', 'null', 33);
INSERT INTO colonias VALUES (215, 'Cointzio [Balneario]', 'null', 33);
INSERT INTO colonias VALUES (216, 'El Edén (Camino al Edén)', 'null', 33);
INSERT INTO colonias VALUES (217, 'El Ejido [Balneario]', 'null', 33);
INSERT INTO colonias VALUES (218, 'Planchapón (Peñas de San Pedro)', 'null', 33);
INSERT INTO colonias VALUES (219, 'Yerbabuena Vieja', 'null', 33);
INSERT INTO colonias VALUES (220, 'La Amargosilla', 'null', 33);
INSERT INTO colonias VALUES (221, 'Campamento de la Presa Cointzio SAGAR INIFAP', 'null', 33);
INSERT INTO colonias VALUES (222, 'Villa Karla', 'null', 33);
INSERT INTO colonias VALUES (223, 'Residencial Mesoamérica', 'null', 33);
INSERT INTO colonias VALUES (224, 'La Cruz', 'null', 33);
INSERT INTO colonias VALUES (225, 'El Ejido de Atapaneo', 'null', 33);
INSERT INTO colonias VALUES (226, 'Fraccionamiento Campestre las Cabañas', 'null', 33);
INSERT INTO colonias VALUES (227, 'Las Granjas (Las Galeras)', 'null', 33);
INSERT INTO colonias VALUES (228, 'Granjas de Barranca Seca', 'null', 33);
INSERT INTO colonias VALUES (229, 'San Rafael [Granja]', 'null', 33);
INSERT INTO colonias VALUES (230, 'Huertitas', 'null', 33);
INSERT INTO colonias VALUES (231, 'Las Juntas', 'null', 33);
INSERT INTO colonias VALUES (232, 'La Lobera', 'null', 33);
INSERT INTO colonias VALUES (233, 'Maderas Aserradas del Canje', 'null', 33);
INSERT INTO colonias VALUES (234, 'Monte Rubio (Borucas)', 'null', 33);
INSERT INTO colonias VALUES (235, 'Unión de Tabiqueros del Río Grande de Morelia', 'null', 33);
INSERT INTO colonias VALUES (236, 'La Peña', 'null', 33);
INSERT INTO colonias VALUES (237, 'Puerto de Pinos', 'null', 33);
INSERT INTO colonias VALUES (238, 'Rancho Maldonado', 'null', 33);
INSERT INTO colonias VALUES (239, 'El Reparo', 'null', 33);
INSERT INTO colonias VALUES (240, 'El Asoleadero (Colonia San José Itzícuaro)', 'null', 33);
INSERT INTO colonias VALUES (241, 'Bello Horizonte', 'null', 33);
INSERT INTO colonias VALUES (242, 'Los Capulines', 'null', 33);
INSERT INTO colonias VALUES (243, 'El Ranchito del Ingeniero', 'null', 33);
INSERT INTO colonias VALUES (244, 'Colonia Benito Juárez', 'null', 33);
INSERT INTO colonias VALUES (245, 'Colonia el Paraíso', 'null', 33);
INSERT INTO colonias VALUES (246, 'Refacciones Usadas Aculco', 'null', 33);
INSERT INTO colonias VALUES (247, 'CRUCO Chapingo (UACH)', 'null', 33);
INSERT INTO colonias VALUES (248, 'Ampliación Torreón Nuevo 6 (Laminadora de Cantera', 'null', 33);
INSERT INTO colonias VALUES (249, 'Ejido Consuelo Alfaro', 'null', 33);
INSERT INTO colonias VALUES (250, 'Sistema Michoacano de Radio y Televisión', 'null', 33);
INSERT INTO colonias VALUES (251, 'Loma Larga', 'null', 33);
INSERT INTO colonias VALUES (252, 'Monasterio Benedictino (La Finca)', 'null', 33);
INSERT INTO colonias VALUES (253, 'Morelia Itzícuaro Tres', 'null', 33);
INSERT INTO colonias VALUES (254, 'Colonia sin Nombre', 'null', 33);
INSERT INTO colonias VALUES (255, 'Ampliación de Torreón Nuevo Siete', 'null', 33);
INSERT INTO colonias VALUES (256, 'Los Álamos', 'null', 33);
INSERT INTO colonias VALUES (257, 'Loma del Salto (Fraccionamiento Loma del Salto)', 'null', 33);
INSERT INTO colonias VALUES (258, 'Colonia Valle de Mil Cumbres', 'null', 33);
INSERT INTO colonias VALUES (259, 'El Caracol', 'null', 33);
INSERT INTO colonias VALUES (260, 'El Reparo', 'null', 33);
INSERT INTO colonias VALUES (261, 'Ampliación de Torreón Nuevo Cuatro', 'null', 33);
INSERT INTO colonias VALUES (262, 'Ampliación de Torreón Nuevo Dos', 'null', 33);
INSERT INTO colonias VALUES (263, 'Ampliación de Torreón Nuevo Tres', 'null', 33);
INSERT INTO colonias VALUES (264, 'Barranca de la Batea', 'null', 33);
INSERT INTO colonias VALUES (265, 'Los Mezquites [Campestre Deportivo]', 'null', 33);
INSERT INTO colonias VALUES (266, 'María Auxiliadora [Casa Hogar]', 'null', 33);
INSERT INTO colonias VALUES (267, 'Rosas de la Infancia [Casa Hogar]', 'null', 33);
INSERT INTO colonias VALUES (268, 'Los Chupaderos', 'null', 33);
INSERT INTO colonias VALUES (269, 'Las Cocinas', 'null', 33);
INSERT INTO colonias VALUES (270, 'Colonia el Resplandor', 'null', 33);
INSERT INTO colonias VALUES (271, 'Colonia Luis Córdova Reyes (Loma Colorada)', 'null', 33);
INSERT INTO colonias VALUES (272, 'Colonia Mirador Purépecha', 'null', 33);
INSERT INTO colonias VALUES (273, 'Colonia Potrero de San Isidro Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (274, 'Fraccionamiento Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (275, 'Fraccionamiento Nueva Era', 'null', 33);
INSERT INTO colonias VALUES (276, 'Kopla [Gasolinería]', 'null', 33);
INSERT INTO colonias VALUES (277, 'Naturaliti (Villa Natura Medicatix) [Hotel]', 'null', 33);
INSERT INTO colonias VALUES (278, 'Instituto de Ecología UNAM', 'null', 33);
INSERT INTO colonias VALUES (279, 'La Noria [Lienzo Charro]', 'null', 33);
INSERT INTO colonias VALUES (280, 'La Lobera', 'null', 33);
INSERT INTO colonias VALUES (281, 'Localidad Sin Nombre', 'null', 33);
INSERT INTO colonias VALUES (282, 'Localidad sin Nombre', 'null', 33);
INSERT INTO colonias VALUES (283, 'Localidad sin nombre', 'null', 33);
INSERT INTO colonias VALUES (284, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (285, 'Lomas de Buenavista', 'null', 33);
INSERT INTO colonias VALUES (286, 'Juan de la Barrera', 'null', 33);
INSERT INTO colonias VALUES (287, 'Colonia el Tepeyac', 'null', 33);
INSERT INTO colonias VALUES (288, 'Palizada', 'null', 33);
INSERT INTO colonias VALUES (289, 'La Palma', 'null', 33);
INSERT INTO colonias VALUES (290, 'Los Paredones Azules', 'null', 33);
INSERT INTO colonias VALUES (291, 'La Pila de San Antonio Parangare', 'null', 33);
INSERT INTO colonias VALUES (292, 'Preparatoria Valladolid', 'null', 33);
INSERT INTO colonias VALUES (293, 'El Ranchito (San Nicolás Obispo)', 'null', 33);
INSERT INTO colonias VALUES (294, 'La Mora', 'null', 33);
INSERT INTO colonias VALUES (295, 'La Providencia', 'null', 33);
INSERT INTO colonias VALUES (296, 'Rancho Prieto (Los Pinos)', 'null', 33);
INSERT INTO colonias VALUES (297, 'Santa María', 'null', 33);
INSERT INTO colonias VALUES (298, 'Villas Lomas del Paraíso', 'null', 33);
INSERT INTO colonias VALUES (299, 'Lázaro Cárdenas [Vivero Forestal]', 'null', 33);
INSERT INTO colonias VALUES (300, 'Colonia Ampliación Zimpanio', 'null', 33);
INSERT INTO colonias VALUES (301, 'Zimpanio Norte Dos', 'null', 33);
INSERT INTO colonias VALUES (302, 'Ampliación la Aldea', 'null', 33);
INSERT INTO colonias VALUES (303, 'Colonia los Encinos Uno', 'null', 33);
INSERT INTO colonias VALUES (304, 'Fraccionamiento Arboledas', 'null', 33);
INSERT INTO colonias VALUES (305, 'Colonia la Palma (Las Palmas)', 'null', 33);
INSERT INTO colonias VALUES (306, 'La Manguita', 'null', 33);
INSERT INTO colonias VALUES (307, 'Tierra Grande', 'null', 33);
INSERT INTO colonias VALUES (308, 'Colonia Asociación Tres de Agosto', 'null', 33);
INSERT INTO colonias VALUES (309, 'Colonia Buenos Aires', 'null', 33);
INSERT INTO colonias VALUES (310, 'Fraccionamiento Ecológico la Campiña', 'null', 33);
INSERT INTO colonias VALUES (311, 'Fraccionamiento los Ángeles (Francisco Villa)', 'null', 33);
INSERT INTO colonias VALUES (312, 'Fraccionamiento Santa Fe', 'null', 33);
INSERT INTO colonias VALUES (313, 'Lomas de la Aldea', 'null', 33);
INSERT INTO colonias VALUES (314, 'Los Llanos', 'null', 33);
INSERT INTO colonias VALUES (315, 'Potrero Nuevo', 'null', 33);
INSERT INTO colonias VALUES (316, 'Fraccionamiento el Sabino', 'null', 33);
INSERT INTO colonias VALUES (317, 'El Pino del Rayo', 'null', 33);
INSERT INTO colonias VALUES (318, 'Colonia sin Nombre', 'null', 33);
INSERT INTO colonias VALUES (319, 'Colonia sin Nombre', 'null', 33);
INSERT INTO colonias VALUES (320, 'Colonia Lomas de Chapultepec (Colonia Torrecillas)', 'null', 33);
INSERT INTO colonias VALUES (321, 'Fraccionamiento el Comal', 'null', 33);
INSERT INTO colonias VALUES (322, 'Fraccionamiento las Cumbres', 'null', 33);
INSERT INTO colonias VALUES (323, 'Fraccionamiento las Peñitas', 'null', 33);
INSERT INTO colonias VALUES (324, 'Fraccionamiento Rinconada los Pirules', 'null', 33);
INSERT INTO colonias VALUES (325, 'Fraccionamiento los Pirules', 'null', 33);
INSERT INTO colonias VALUES (326, 'Trojes de Izcalán', 'null', 33);
INSERT INTO colonias VALUES (327, 'Villa Magna', 'null', 33);
INSERT INTO colonias VALUES (328, 'La Lagunita', 'null', 33);
INSERT INTO colonias VALUES (329, 'Colonia Centenario', 'null', 33);
INSERT INTO colonias VALUES (330, 'Colonia Unidad Satélite', 'null', 33);
INSERT INTO colonias VALUES (331, 'Fraccionamiento el Escobal', 'null', 33);
INSERT INTO colonias VALUES (332, 'Arcos de San Juan', 'null', 33);
INSERT INTO colonias VALUES (333, 'Nigromante', 'null', 33);
INSERT INTO colonias VALUES (334, 'Villas de la Loma', 'null', 33);
INSERT INTO colonias VALUES (335, 'San Antonio', 'null', 33);
INSERT INTO colonias VALUES (336, 'Tres Marías', 'null', 33);
INSERT INTO colonias VALUES (337, 'Fraccionamiento de la Luz', 'null', 33);
INSERT INTO colonias VALUES (338, 'Gregorio Patiño', 'null', 33);
INSERT INTO colonias VALUES (339, 'Fraccionamiento Misión del Valle', 'null', 33);
INSERT INTO colonias VALUES (340, 'ARKO San Mateo', 'null', 33);
INSERT INTO colonias VALUES (341, 'Camino del Rey', 'null', 33);
INSERT INTO colonias VALUES (342, 'El Charaquendo', 'null', 33);
INSERT INTO colonias VALUES (343, 'Ampliación Torreón Nuevo', 'null', 33);
INSERT INTO colonias VALUES (344, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (345, 'Fraccionamiento la Nueva Aldea', 'null', 33);
INSERT INTO colonias VALUES (346, 'Jesús González Ortega', 'null', 33);
INSERT INTO colonias VALUES (347, 'Ejido San Isidro Itzícuaro (La Ladera 2)', 'null', 33);
INSERT INTO colonias VALUES (348, 'Fraccionamiento Cerro Verde', 'null', 33);
INSERT INTO colonias VALUES (349, 'Fraccionamiento San Isidro Itzícuaro', 'null', 33);
INSERT INTO colonias VALUES (350, 'Fraccionamiento Villas del Sur', 'null', 33);
INSERT INTO colonias VALUES (351, 'La Mora', 'null', 33);
INSERT INTO colonias VALUES (352, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (353, 'Valle la Hacienda (El Mezquite)', 'null', 33);
INSERT INTO colonias VALUES (354, 'Bosque Monarca', 'null', 33);
INSERT INTO colonias VALUES (355, 'Fraccionamiento la Condesa', 'null', 33);
INSERT INTO colonias VALUES (356, 'Cerro Blanco', 'null', 33);
INSERT INTO colonias VALUES (357, 'Conjunto Habitacional la Hacienda', 'null', 33);
INSERT INTO colonias VALUES (358, 'Conjunto Habitacional Villas del Pedregal', 'null', 33);
INSERT INTO colonias VALUES (359, 'Ejido Cuitzillo Grande', 'null', 33);
INSERT INTO colonias VALUES (360, 'El Jamanal', 'null', 33);
INSERT INTO colonias VALUES (361, 'El Pedregal', 'null', 33);
INSERT INTO colonias VALUES (362, 'Fraccionamiento Jardines de Iratzio', 'null', 33);
INSERT INTO colonias VALUES (363, 'Fraccionamiento la Nueva Aldea (Fracción C)', 'null', 33);
INSERT INTO colonias VALUES (364, 'Fraccionamiento La Nueva Aldea (Fracción E)', 'null', 33);
INSERT INTO colonias VALUES (365, 'Fraccionamiento los Jilgueros', 'null', 33);
INSERT INTO colonias VALUES (366, 'La Nueva Aldea Segunda Etapa', 'null', 33);
INSERT INTO colonias VALUES (367, 'Lago del ParaÍso', 'null', 33);
INSERT INTO colonias VALUES (368, 'Las Peñitas', 'null', 33);
INSERT INTO colonias VALUES (369, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (370, 'Ejidal Santa María', 'null', 33);
INSERT INTO colonias VALUES (371, 'Cuitzillo', 'null', 33);
INSERT INTO colonias VALUES (372, 'La Longaniza (Las Mesas)', 'null', 33);
INSERT INTO colonias VALUES (373, 'Nicolás Bravo', 'null', 33);
INSERT INTO colonias VALUES (374, 'Montaña Monarca (Punta Altozano)', 'null', 33);
INSERT INTO colonias VALUES (375, 'Cañadas del Bosque', 'null', 33);
INSERT INTO colonias VALUES (376, 'Residencial Fresnos', 'null', 33);
INSERT INTO colonias VALUES (377, 'Mirador Valladolid', 'null', 33);
INSERT INTO colonias VALUES (378, 'Bosques de Atécuaro', 'null', 33);
INSERT INTO colonias VALUES (379, 'Cascadas de Ichaqueo [Parque Ecoturístico]', 'null', 33);
INSERT INTO colonias VALUES (380, 'La Esperanza', 'null', 33);
INSERT INTO colonias VALUES (381, 'Fraccionamiento Huertos de Atapaneo', 'null', 33);
INSERT INTO colonias VALUES (382, 'Ejido Torrecillas', 'null', 33);
INSERT INTO colonias VALUES (383, 'Fraccionamiento Ignacio Allende', 'null', 33);
INSERT INTO colonias VALUES (384, 'Puerta Blanca', 'null', 33);
INSERT INTO colonias VALUES (385, 'Quinta María José', 'null', 33);
INSERT INTO colonias VALUES (386, 'Carindapaz (San Francisco) [Invernadero]', 'null', 33);
INSERT INTO colonias VALUES (387, 'San Antonio', 'null', 33);
INSERT INTO colonias VALUES (388, 'La Irla del Padre', 'null', 33);
INSERT INTO colonias VALUES (389, 'Ojo de Agua', 'null', 33);
INSERT INTO colonias VALUES (390, 'Fraccionamiento Bosques de la Ribera', 'null', 33);
INSERT INTO colonias VALUES (391, 'El Aserradero', 'null', 33);
INSERT INTO colonias VALUES (392, 'El Renoval', 'null', 33);
INSERT INTO colonias VALUES (393, 'Puerto los Copales (Los Copales)', 'null', 33);
INSERT INTO colonias VALUES (394, 'Fraccionamiento Villa Coapa Dos', 'null', 33);
INSERT INTO colonias VALUES (395, 'Fraccionamiento San Lorenzo', 'null', 33);
INSERT INTO colonias VALUES (396, 'La Cuesta', 'null', 33);
INSERT INTO colonias VALUES (397, 'El Barretero Primera Etapa', 'null', 33);
INSERT INTO colonias VALUES (398, 'Casa Real', 'null', 33);
INSERT INTO colonias VALUES (399, 'Fraccionamiento la Loma', 'null', 33);
INSERT INTO colonias VALUES (400, 'Fraccionamiento Río Florido', 'null', 33);
INSERT INTO colonias VALUES (401, 'Fraccionamiento Cerrito de San José', 'null', 33);
INSERT INTO colonias VALUES (402, 'Bello Amanecer', 'null', 33);
INSERT INTO colonias VALUES (403, 'Monte Vista (Monte Bello)', 'null', 33);
INSERT INTO colonias VALUES (404, 'Colonia Heriberto Castillo Martínez', 'null', 33);
INSERT INTO colonias VALUES (405, 'Colonia San Javier Xanamoro', 'null', 33);
INSERT INTO colonias VALUES (406, 'Colonia 2 de Marzo', 'null', 33);
INSERT INTO colonias VALUES (407, 'Fraccionamiento Agua Nueva (Fraccionamiento San Isidro Tres)', 'null', 33);
INSERT INTO colonias VALUES (408, 'Ejido la Quemada', 'null', 33);
INSERT INTO colonias VALUES (409, 'Joyitas del Valle', 'null', 33);
INSERT INTO colonias VALUES (410, 'La Tranca', 'null', 33);
INSERT INTO colonias VALUES (411, 'Cumbres de Capula', 'null', 33);
INSERT INTO colonias VALUES (412, 'Albergue de Indigentes para Enfermos Mentales', 'null', 33);
INSERT INTO colonias VALUES (413, 'Fraccionamiento San Miguel', 'null', 33);
INSERT INTO colonias VALUES (414, 'San Carlos', 'null', 33);
INSERT INTO colonias VALUES (415, 'San Pedro', 'null', 33);
INSERT INTO colonias VALUES (416, 'Imperio Purépecha', 'null', 33);
INSERT INTO colonias VALUES (417, 'Lomas de Torreón', 'null', 33);
INSERT INTO colonias VALUES (418, 'Quinceo II', 'null', 33);
INSERT INTO colonias VALUES (419, 'Villa Universo', 'null', 33);
INSERT INTO colonias VALUES (420, 'Paseo del Refugio', 'null', 33);
INSERT INTO colonias VALUES (421, 'El Olival', 'null', 33);
INSERT INTO colonias VALUES (422, 'Princesa Mintzita [Ampliación]', 'null', 33);
INSERT INTO colonias VALUES (423, 'Ciudad Peluche (La Quebradita)', 'null', 33);
INSERT INTO colonias VALUES (424, 'La Purísima [Colonia]', 'null', 33);
INSERT INTO colonias VALUES (425, 'Luviano [Fraccionamiento]', 'null', 33);
INSERT INTO colonias VALUES (426, 'Praderas Cuitzillo', 'null', 33);
INSERT INTO colonias VALUES (427, 'Humberto Gutiérrez Corona [Colonia]', 'null', 33);
INSERT INTO colonias VALUES (428, 'Ninguno', 'null', 33);
INSERT INTO colonias VALUES (429, 'Villa Dorada [Colonia]', 'null', 33);
INSERT INTO colonias VALUES (430, 'Ruben Jaramillo [Colonia Primera Etapa]', 'null', 33);
INSERT INTO colonias VALUES (431, 'Ruben Jaramillo [Colonia Segunda Etapa]', 'null', 33);
INSERT INTO colonias VALUES (432, 'Ampliación Palma de Tacícuaro', 'null', 33);
INSERT INTO colonias VALUES (433, 'Verónica López 3ra. Etapa [Colonia]', 'null', 33);
INSERT INTO municipios VALUES (34, 'Múgica', 1);
INSERT INTO municipios VALUES (35, 'Ecuandureo', 1);
INSERT INTO municipios VALUES (36, 'Buenavista', 1);
INSERT INTO municipios VALUES (37, 'Villamar', 1);
INSERT INTO municipios VALUES (38, 'Morelos', 1);
INSERT INTO municipios VALUES (39, 'Tingüindín', 1);
INSERT INTO municipios VALUES (40, 'Susupuato', 1);
INSERT INTO municipios VALUES (41, 'Tangamandapio', 1);
INSERT INTO municipios VALUES (42, 'Paracho', 1);
INSERT INTO municipios VALUES (43, 'Nuevo Urecho', 1);
INSERT INTO municipios VALUES (44, 'Pajacuarán', 1);
INSERT INTO municipios VALUES (45, 'Cotija', 1);
INSERT INTO municipios VALUES (46, 'Lázaro Cárdenas', 1);
INSERT INTO municipios VALUES (47, 'Zacapu', 1);
INSERT INTO municipios VALUES (48, 'Ixtlán', 1);
INSERT INTO municipios VALUES (49, 'Tacámbaro', 1);
INSERT INTO municipios VALUES (50, 'Chucándiro', 1);
INSERT INTO municipios VALUES (51, 'Los Reyes', 1);
INSERT INTO municipios VALUES (52, 'Juárez', 1);
INSERT INTO municipios VALUES (53, 'Aporo', 1);
INSERT INTO municipios VALUES (54, 'Tiquicheo de Nicolás Romero', 1);
INSERT INTO municipios VALUES (55, 'Nahuatzen', 1);
INSERT INTO municipios VALUES (56, 'Tingambato', 1);
INSERT INTO municipios VALUES (57, 'Yurécuaro', 1);
INSERT INTO municipios VALUES (58, 'Carácuaro', 1);
INSERT INTO municipios VALUES (59, 'Coahuayana', 1);
INSERT INTO municipios VALUES (60, 'Tanhuato', 1);
INSERT INTO municipios VALUES (61, 'Tepalcatepec', 1);
INSERT INTO municipios VALUES (62, 'Pátzcuaro', 1);
INSERT INTO municipios VALUES (63, 'Marcos Castellanos', 1);
INSERT INTO municipios VALUES (64, 'Epitacio Huerta', 1);
INSERT INTO municipios VALUES (65, 'Coalcomán de Vázquez Pallares', 1);
INSERT INTO municipios VALUES (66, 'Tancítaro', 1);
INSERT INTO municipios VALUES (67, 'Apatzingán', 1);
INSERT INTO municipios VALUES (68, 'Erongarícuaro', 1);
INSERT INTO municipios VALUES (69, 'La Huacana', 1);
INSERT INTO municipios VALUES (70, 'Angamacutiro', 1);
INSERT INTO municipios VALUES (71, 'Zinapécuaro', 1);
INSERT INTO municipios VALUES (72, 'Queréndaro', 1);
INSERT INTO municipios VALUES (73, 'La Piedad', 1);
INSERT INTO municipios VALUES (74, 'Contepec', 1);
INSERT INTO municipios VALUES (75, 'Acuitzio', 1);
INSERT INTO municipios VALUES (76, 'Jiménez', 1);
INSERT INTO municipios VALUES (77, 'Puruándiro', 1);
INSERT INTO municipios VALUES (78, 'Quiroga', 1);
INSERT INTO municipios VALUES (79, 'Tlalpujahua', 1);
INSERT INTO municipios VALUES (80, 'Ario', 1);
INSERT INTO municipios VALUES (81, 'Chinicuila', 1);
INSERT INTO municipios VALUES (82, 'Senguio', 1);
INSERT INTO municipios VALUES (83, 'Taretan', 1);
INSERT INTO municipios VALUES (84, 'Aquila', 1);
INSERT INTO municipios VALUES (85, 'Maravatío', 1);
INSERT INTO municipios VALUES (86, 'Chilchota', 1);
INSERT INTO municipios VALUES (87, 'San Lucas', 1);
INSERT INTO municipios VALUES (88, 'Jungapeo', 1);
INSERT INTO municipios VALUES (89, 'Ziracuaretiro', 1);
INSERT INTO municipios VALUES (90, 'Vista Hermosa', 1);
INSERT INTO municipios VALUES (91, 'Huaniqueo', 1);
INSERT INTO municipios VALUES (92, 'Irimbo', 1);
INSERT INTO municipios VALUES (93, 'Charo', 1);
INSERT INTO municipios VALUES (94, 'Tocumbo', 1);
INSERT INTO municipios VALUES (95, 'Jiquilpan', 1);
INSERT INTO municipios VALUES (96, 'Churintzio', 1);
INSERT INTO municipios VALUES (97, 'Zitácuaro', 1);
INSERT INTO municipios VALUES (98, 'Tzitzio', 1);
INSERT INTO municipios VALUES (99, 'Indaparapeo', 1);
INSERT INTO municipios VALUES (100, 'Hidalgo', 1);
INSERT INTO municipios VALUES (101, 'Peribán', 1);
INSERT INTO municipios VALUES (102, 'Huiramba', 1);
INSERT INTO municipios VALUES (103, 'Nocupétaro', 1);
INSERT INTO municipios VALUES (104, 'Briseñas', 1);
INSERT INTO municipios VALUES (105, 'Madero', 1);
INSERT INTO municipios VALUES (106, 'Zamora', 1);
INSERT INTO municipios VALUES (107, 'Turicato', 1);
INSERT INTO municipios VALUES (108, 'Churumuco', 1);
INSERT INTO municipios VALUES (109, 'Chavinda', 1);
INSERT INTO municipios VALUES (110, 'Jacona', 1);
INSERT INTO municipios VALUES (111, 'Santa Ana Maya', 1);
INSERT INTO municipios VALUES (112, 'Zináparo', 1);
INSERT INTO municipios VALUES (113, 'Numarán', 1);
INSERT INTO municipios VALUES (114, 'Huandacareo', 1);
