INSERT INTO profesores (nombre) VALUES ('Mora Garcia Jorge');
INSERT INTO profesores (nombre) VALUES ('Huerta Cortes Andres Ivan');
INSERT INTO profesores (nombre) VALUES ('Pacheco Pimentel Efren de Jesus');
INSERT INTO profesores (nombre) VALUES ('Mora Tenorio Sandra');
INSERT INTO profesores (nombre) VALUES ('Gallegos Perez Joxim');
INSERT INTO profesores (nombre) VALUES ('Florian Ernesto Claudio Ernesto');
INSERT INTO profesores (nombre) VALUES ('Sanchez Vega Jorge');
INSERT INTO profesores (nombre) VALUES ('Florian Arenas Claudio Ernesto');
INSERT INTO profesores (nombre) VALUES ('Antolino Hernandez Anastacio');
INSERT INTO profesores (nombre) VALUES ('Amaro Flores Alejandro');
INSERT INTO profesores (nombre) VALUES ('Ortiz Ortiz Octavio Salud');
INSERT INTO profesores (nombre) VALUES ('Chavez Jacobo Victor Manuel');
INSERT INTO profesores (nombre) VALUES ('Rios Ponce Juan');
INSERT INTO profesores (nombre) VALUES ('Calderon Cortez Javier');
INSERT INTO profesores (nombre) VALUES ('Alcaraz Chaves Jesus Eduardo');
INSERT INTO profesores (nombre) VALUES ('Flores Tinoco Alma Lilia Deni');
INSERT INTO profesores (nombre) VALUES ('Morales Lopez Felipe');
INSERT INTO profesores (nombre) VALUES ('Lopez Torres Joel');
INSERT INTO profesores (nombre) VALUES ('Villagomez Cardenas Salvador Jonathan');
INSERT INTO profesores (nombre) VALUES ('Jimenez Murillo Jose Alfredo');
INSERT INTO profesores (nombre) VALUES ('Tapia Colin Luis Enrique');
INSERT INTO profesores (nombre) VALUES ('Blancas Martinez Monica Adriana');
INSERT INTO profesores (nombre) VALUES ('Lopez Ruiz Manuel');
INSERT INTO profesores (nombre) VALUES ('Hernandez Esquivel Jose Omar');
INSERT INTO profesores (nombre) VALUES ('Guzman Marines Raymundo');
INSERT INTO profesores (nombre) VALUES ('Manzo Mora Reynaldo');
INSERT INTO profesores (nombre) VALUES ('Robledo Torrecilla Eva Maria');
INSERT INTO profesores (nombre) VALUES ('Rodriguez Baltazar Margarita');
INSERT INTO profesores (nombre) VALUES ('Atienzo de la Cruz Mora Lizeth');
INSERT INTO profesores (nombre) VALUES ('Felix Escalona Samuel');
INSERT INTO profesores (nombre) VALUES ('Duran Ibarra Miguel Alberto');
INSERT INTO profesores (nombre) VALUES ('Martinez Rosiles Carol Aidee');
INSERT INTO profesores (nombre) VALUES ('Garcia Ramirez Maria del Carmen');
INSERT INTO profesores (nombre) VALUES ('Casimiro Linares Edgar');
INSERT INTO profesores (nombre) VALUES ('Ramos Diaz J. Guadalupe');
INSERT INTO profesores (nombre) VALUES ('Hugo Fernando Hernandez Lopez');
INSERT INTO profesores (nombre) VALUES ('Amauri Cortes Coria');
INSERT INTO profesores (nombre) VALUES ('Lara Barcenas Ruben');
INSERT INTO profesores (nombre) VALUES ('Viacava Breiding Fernando Pedro');
INSERT INTO profesores (nombre) VALUES ('Rojas Prospero Ireri Tsipekua');
INSERT INTO profesores (nombre) VALUES ('Millarez Torres Cristhian');
INSERT INTO profesores (nombre) VALUES ('Rodriguez Tapia Marco Alonso');
INSERT INTO profesores (nombre) VALUES ('Perez Arreola Cesar Alejandro');
INSERT INTO profesores (nombre) VALUES ('Vaca Astorga Jordi');
INSERT INTO profesores (nombre) VALUES ('Solis Robles Juan Javier');