INSERT INTO profesores VALUES (1, 'Huerta Cortes Andres Ivan');
INSERT INTO asignaturas VALUES (1, 'Analisis de Señales y Sistemas de Comunicacion', 'B5T1', 'A', 5, 5, 5, '', '', '', '', '', '', '', '', '', '', 97, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 1);
INSERT INTO profesores VALUES (2, 'Pacheco Pimentel Efren de Jesus');
INSERT INTO asignaturas VALUES (2, 'Redes de Computadoras', 'B5T3', 'A', 5, 5, 4, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 2);
INSERT INTO profesores VALUES (3, 'Mora Tenorio Sandra');
INSERT INTO asignaturas VALUES (3, 'Arquitectura de Computadoras', 'B5T5', 'A', 4, 5, 4, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 3);
INSERT INTO profesores VALUES (4, 'Gallegos Perez Joxim');
INSERT INTO asignaturas VALUES (4, 'Bases de Datos Distribuidas', 'B5T4', 'A', 5, 5, 5, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 4);
INSERT INTO profesores VALUES (5, 'Florian Ernesto Claudio Ernesto');
INSERT INTO asignaturas VALUES (5, 'Taller de Ingenieria en Software', 'B5T6', 'A', 4, 5, 5, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 5);
INSERT INTO profesores VALUES (6, 'Sanchez Vega Jorge');
INSERT INTO asignaturas VALUES (6, 'Administracion de Proyectos', 'B5T2', 'A', 5, 5, 4, '', '', '', '', '', '', '', '', '', '', 88, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 6);
INSERT INTO profesores VALUES (7, 'NA');
INSERT INTO asignaturas VALUES (7, 'Actividades Complementarias', 'B9T1', 'A', 5, 7, 5, '', '', '', '', '', '', '', '', '', '', null, 'AD', 'AD', 'AD', 7);
INSERT INTO profesores VALUES (8, 'Florian Arenas Claudio Ernesto');
INSERT INTO asignaturas VALUES (8, 'Negocios Electronicos I', 'B7T5', 'A', 4, 7, 5, '', '', '', '', '', '', '', '', '', '', 100, '01', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 8);
INSERT INTO asignaturas VALUES (9, 'Sistemas Operativos II', 'B7T4', '', 5, 7, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO profesores VALUES (9, 'Antolino Hernandez Anastacio');
INSERT INTO asignaturas VALUES (10, 'Introduccion a la Seguridad de la Informacion', 'B7T7', 'A', 5, 7, 6, '13:00-14:00', '13:00-14:00', '13:00-14:00', '13:00-14:00', '13:00-14:00', 'F6', 'F6', 'F6', 'F6', 'F6', null, '', '', '', 9);
INSERT INTO profesores VALUES (10, 'Amaro Flores Alejandro');
INSERT INTO asignaturas VALUES (11, 'Desarrollo de Aplicaciones para Dispositivos Moviles', 'B7T2', 'A', 5, 7, 6, '18:00-19:00', '18:00-19:00', '', '18:00-20:00', '', 'LIS', 'LIS', '', 'LIS', '', null, '', '', '', 10);
INSERT INTO profesores VALUES (11, 'Ortiz Ortiz Octavio Salud');
INSERT INTO asignaturas VALUES (12, 'Taller de Investigacion I', 'B7T3', 'A', 4, 7, 6, '14:00-15:00', '14:00-15:00', '14:00-15:00', '14:00-15:00', '', 'F1', 'F1', 'F1', 'F1', '', null, '', '', '', 11);
INSERT INTO profesores VALUES (12, 'Mora Garcia Jorge');
INSERT INTO asignaturas VALUES (13, 'Redes Emergentes', 'B7T1', 'A', 5, 7, 6, '16:00-17:00', '16:00-17:00', '16:00-17:00', '16:00-17:00', '16:00-17:00', 'F1', 'F1', 'LRD', 'F1', 'LRD', null, '', '', '', 12);
INSERT INTO profesores VALUES (13, 'Chavez Jacobo Victor Manuel');
INSERT INTO asignaturas VALUES (14, 'Desarrollo Sustentable', 'B6T5', 'B', 5, 3, 4, '', '', '', '', '', '', '', '', '', '', 95, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 13);
INSERT INTO profesores VALUES (14, 'Rios Ponce Juan');
INSERT INTO asignaturas VALUES (15, 'Matematicas para la Toma de Desiciones', 'B3T3', 'A', 5, 3, 3, '', '', '', '', '', '', '', '', '', '', 94, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 14);
INSERT INTO profesores VALUES (15, 'Calderon Cortez Javier');
INSERT INTO asignaturas VALUES (16, 'Electricidad y Magnetismo', 'B3TA', 'AB', 0, 3, 2, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 15);
INSERT INTO profesores VALUES (16, 'Alcaraz Chaves Jesus Eduardo');
INSERT INTO asignaturas VALUES (17, 'Estructura y Organizacion de Datos', 'B3T2', 'A', 5, 3, 3, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 16);
INSERT INTO profesores VALUES (17, 'Gallegos Perez Joxim');
INSERT INTO asignaturas VALUES (18, 'Fundamentos de Base de Datos', 'B3T4', 'A', 5, 3, 3, '', '', '', '', '', '', '', '', '', '', 95, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 17);
INSERT INTO profesores VALUES (18, 'Flores Tinoco Alma Lilia Deni');
INSERT INTO asignaturas VALUES (19, 'Electricidad y Magnetismo', 'B3T5', 'A', 4, 3, 2, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 18);
INSERT INTO profesores VALUES (19, 'Lopez Torres Joel');
INSERT INTO asignaturas VALUES (20, 'Administracion Gerencial', 'B3T6', 'A', 4, 3, 3, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 19);
INSERT INTO profesores VALUES (20, 'Jimenez Murillo Jose Alfredo');
INSERT INTO asignaturas VALUES (21, 'Matematicas Discretas I', 'B1T3', 'A', 5, 1, 1, '16:00-17:00', '16:00-17:00', '16:00-17:00', '16:00-17:00', '16:00-17:00', 'F6', 'F6', 'F6', 'F6', 'F6', 70, 'R1', 'Evaluacion Regularizacion Primera Vez', 'Curso Aprobado', 20);
INSERT INTO profesores VALUES (21, 'Tapia Colin Luis Enrique');
INSERT INTO asignaturas VALUES (22, 'Calculo Diferencial', 'B1T1', 'A', 5, 1, 1, '17:00-18:00', '17:00-18:00', '17:00-18:00', '17:00-18:00', '17:00-18:00', 'F6', 'F6', 'F6', 'F6', 'F6', 73, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 21);
INSERT INTO profesores VALUES (22, 'Blancas Martinez Monica Adriana');
INSERT INTO asignaturas VALUES (23, 'Fundamentos de Investigacion', 'B1T6', 'A', 4, 1, 1, '14:00-15:00', '14:00-15:00', '14:00-15:00', '14:00-15:00', '', 'F6', 'F6', 'F6', 'F6', '', 86, 'R1', 'Evaluacion Regularizacion Primera Vez', 'Curso Aprobado', 22);
INSERT INTO profesores VALUES (23, 'Lopez Ruiz Manuel');
INSERT INTO asignaturas VALUES (24, 'Fundamentos de Programacion', 'B1T2', 'A', 5, 1, 1, '18:00-19:00', '18:00-19:00', '18:00-19:00', '18:00-19:00', '', 'LC3', 'F6', 'F6', 'LC3', '', 93, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 23);
INSERT INTO profesores VALUES (24, 'Hernandez Esquivel Jose Omar');
INSERT INTO asignaturas VALUES (25, 'Taller de Etica', 'B1T5', 'A', 4, 1, 1, '15:00-16:00', '15:00-16:00', '15:00-16:00', '15:00-16:00', '', 'F6', 'F6', 'F6', 'F6', '', 70, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 24);
INSERT INTO profesores VALUES (25, 'Hernandez Esquivel Jose Omar');
INSERT INTO asignaturas VALUES (26, 'Introduccion a las TICs', 'B1T4', 'A', 3, 1, 1, '19:00-20:00', '19:00-20:00', '19:00-20:00', '', '', 'F6', 'F6', 'F6', '', '', 83, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 25);
INSERT INTO asignaturas VALUES (27, 'Seguridad en Redes', 'B9T7', '', 5, 9, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (28, 'Sistemas de Gestion de la Seguridad Informatica', 'B9T8', '', 5, 9, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (29, 'Ingenieria del Conocimiento', 'B8T4', '', 5, 9, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (30, 'Residencias Profesionales', 'B9T3', '', 10, 9, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO profesores VALUES (26, 'Guzman Marines Raymundo');
INSERT INTO asignaturas VALUES (31, 'Programacion Orientada a Objetos', 'B2T2', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 26);
INSERT INTO profesores VALUES (27, 'Manzo Mora Reynaldo');
INSERT INTO asignaturas VALUES (32, 'Algebra Lineal', 'B2T4', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 95, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 27);
INSERT INTO profesores VALUES (28, 'Rodriguez Baltazar Margarita');
INSERT INTO asignaturas VALUES (33, 'Probabilidad y Estadistica', 'B2T5', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 87, 'R1', 'Evaluacion Regularizacion Primera Vez', 'Curso Aprobado', 28);
INSERT INTO profesores VALUES (29, 'Atienzo de la Cruz Nora Lizeth');
INSERT INTO asignaturas VALUES (34, 'Calculo Integral', 'B2T1', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 90, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 29);
INSERT INTO profesores VALUES (30, 'Duran Ibarra Miguel Alberto');
INSERT INTO asignaturas VALUES (35, 'Contabilidad y Costos', 'B2T6', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 89, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 30);
INSERT INTO profesores VALUES (31, 'Ortiz Ortiz Octavio Salud');
INSERT INTO asignaturas VALUES (36, 'Matematicas Discretas II', 'B2T3', 'A', 5, 2, 2, '', '', '', '', '', '', '', '', '', '', 95, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 31);
INSERT INTO profesores VALUES (32, 'Martinez Rosiles Carol Aidee');
INSERT INTO asignaturas VALUES (37, 'Ingenieria de Software', 'B4T6', 'A', 4, 4, 4, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 32);
INSERT INTO profesores VALUES (33, 'Garcia Ramirez Maria del Carmen');
INSERT INTO asignaturas VALUES (38, 'Circuitos Electricos y Electronicos', 'B4T5', 'A', 5, 4, 3, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 33);
INSERT INTO profesores VALUES (34, 'Casimiro Linares Edgar');
INSERT INTO asignaturas VALUES (39, 'Matematicas Aplicadas a Comunicaciones', 'B4T1', 'A', 5, 4, 3, '', '', '', '', '', '', '', '', '', '', 95, 'R1', 'Evaluacion Regularizacion Primera Vez', 'Curso Aprobado', 34);
INSERT INTO profesores VALUES (35, 'Ramos Diaz J. Guadalupe');
INSERT INTO asignaturas VALUES (40, 'Programacion II', 'B4T2', 'A', 5, 4, 4, '', '', '', '', '', '', '', '', '', '', 98, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 35);
INSERT INTO profesores VALUES (36, 'Morales Lopez Felipe');
INSERT INTO asignaturas VALUES (41, 'Taller de Base de Datos', 'B4T4', 'A', 5, 4, 4, '', '', '', '', '', '', '', '', '', '', 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 36);
INSERT INTO profesores VALUES (37, 'Lara Barcenas Ruben');
INSERT INTO asignaturas VALUES (42, 'Fundamentos de Redes', 'B4T3', 'A', 5, 4, 3, '', '', '', '', '', '', '', '', '', '', 98, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 37);
INSERT INTO profesores VALUES (38, 'Rojas Prospero Ireri Tsipekua');
INSERT INTO asignaturas VALUES (43, 'Tecnologias Inalambricas', 'B6T6', 'A', 4, 6, 5, '', '', '', '', '', '', '', '', '', '', 94, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 38);
INSERT INTO profesores VALUES (39, 'Millarez Torres Cristhian');
INSERT INTO asignaturas VALUES (44, 'Telecomunicaciones', 'B6T1', 'A', 5, 6, 6, '11:00-12:00', '11:00-12:00', '11:00-12:00', '11:00-12:00', '11:00-12:00', 'F4', 'F4', 'F4', 'F4', 'LRD', null, '', '', '', 39);
INSERT INTO profesores VALUES (40, 'Rodriguez Tapia Marco Alonso');
INSERT INTO asignaturas VALUES (45, 'Interaccion Humano Computadora', 'B7T6', 'A', 4, 6, 4, '', '', '', '', '', '', '', '', '', '', 99, '01', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 40);
INSERT INTO profesores VALUES (41, 'Perez Arreola Cesar Alejandro');
INSERT INTO asignaturas VALUES (46, 'Programacion Web', 'B6T2', 'A', 5, 6, 5, '', '', '', '', '', '', '', '', '', '', 100, '01', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 41);
INSERT INTO profesores VALUES (42, 'Hernandez Esquivel Jose Omar');
INSERT INTO asignaturas VALUES (47, 'Sistemas Operativos I', 'B6T4', 'A', 4, 6, 6, '12:00-13:00', '12:00-13:00', '12:00-13:00', '12:00-13:00', '', 'F5', 'F5', 'F5', 'F5', '', null, '', '', '', 42);
INSERT INTO profesores VALUES (43, 'Viacava Breiding Fernando Pedro');
INSERT INTO asignaturas VALUES (48, 'Desarrollo de Emprendedores', 'B6T3', 'A', 5, 6, 4, '', '', '', '', '', '', '', '', '', '', 88, '01', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado', 43);
INSERT INTO asignaturas VALUES (49, 'Auditoria en Tecnologias de la Informacion', 'B8T2', '', 5, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO profesores VALUES (44, 'Lara Barcenas Ruben');
INSERT INTO asignaturas VALUES (50, 'Administracion y Seguridad de Redes', 'B8T1', 'A', 5, 8, 6, '8:00-10:00', '8:00-10:00', '8:00-10:00', '', '8:00-10:00', 'LRD', 'F3', 'F3', '', 'F3', null, '', '', '', 44);
INSERT INTO asignaturas VALUES (51, 'Computo en la Nube', 'B8T8', '', 5, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (52, 'Negocios Electronicos II', 'B8T5', '', 5, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (53, 'Taller de Investigacion II', 'B8T3', '', 5, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (54, 'Servicio Social', 'B9T2', '', 10, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
INSERT INTO asignaturas VALUES (55, 'Seguridad en Sistemas Operativos', 'B8T9', '', 5, 8, 0, '', '', '', '', '', '', '', '', '', '', null, '', '', '', null);
