INSERT INTO asignaturas VALUES (1, 'Arquitectura de Computadoras', 'B5T5', 'B', 4, 5, 4, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (2, 'Analisis de Señales y Sistemas de Comunicacion', 'B5T1', 'A', 5, 5, 5, 97, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (3, 'Redes de Computadoras', 'B5T3', 'A', 5, 5, 4, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (4, 'Redes de Computadoras', 'B5T3', 'B', 5, 5, 4, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (5, 'Arquitectura de Computadoras', 'B5T5', 'A', 4, 5, 4, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (6, 'Bases de Datos Distribuidas', 'B5T4', 'A', 5, 5, 5, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (7, 'Taller de Ingenieria en Software', 'B5T6', 'A', 4, 5, 5, 100, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (8, 'Administracion de Proyectos', 'B5T2', 'B', 5, 5, 4, 88, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (9, 'Analisis de Señales y Sistemas de Comunicacion', 'B5T1', 'B', 5, 5, 5, 97, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (10, 'Administracion de Proyectos', 'B5T2', 'A', 5, 5, 4, 88, 'O1', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (11, 'Actividades Complementarias', 'B9T1', 'A', 5, 7, 5, ACA, 'AD', 'AD', 'AD');
INSERT INTO asignaturas VALUES (12, 'Negocios Electronicos I', 'B7T5', 'A', 4, 7, 5, 100, '01', 'Evaluacion Ordinaria Primera Vez', 'Curso Aprobado');
INSERT INTO asignaturas VALUES (13, 'Sistemas Operativos II', 'B7T4', '', 5, 7, None, null, '', '', '');
INSERT INTO asignaturas VALUES (14, 'Introduccion a la Seguridad de la Informacion', 'B7T7', 'A', 5, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (15, 'Desarrollo de Aplicaciones para Dispositivos Moviles', 'B7T2', 'A', 5, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (16, 'Taller de Investigacion I', 'B7T3', 'A', 4, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (17, 'Redes Emergentes', 'B7T1', 'A', 5, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (18, 'Redes Emergentes', 'B7T1', 'B', 5, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (19, 'Desarrollo de Aplicaciones para Dispositivos Moviles', 'B7T2', 'B', 5, 7, 6, null, '', '', '');
INSERT INTO asignaturas VALUES (20, 'Introduccion a la Seguridad de la Informacion', 'B7T7', 'B', 5, 7, 6, null, '', '', '');
