./gradlew downloadApolloSchema \
  --endpoint="http://localhost:9090/graphql" \
  --schema="app/src/main/graphql/schema.json" \
  --header="Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MjMwNDA1NTAsImV4cCI6MTYyMzA0Nzc1MCwiaWRBbHVtbm8iOiIxNTc1YzY3Zi1lMjQ4LTQ2YmItOGNjNy03NDgyNzhmMzNiNmEiLCJjb3JyZW8iOiJzbWFkQGdtYWlsLmNvbSAgICAgICAgICAgICAgICAgICAgICIsIm5vbWJyZSI6IkNhcmxvcyBTZWJhc3RpYW4gTWFkcmlnYWwgUm9kcmlndWV6Iiwibm9Db250cm9sIjoiMTgxMjE2OTkgICJ9.edOy-DdJ_F6n86T2f00JzKjq2i-SmL-6HV4N5eYrzvBjUnkH6fem3Yl8DOKUXQzeFW_ZKrf6W6W8ce7-XKMjQg"
