./gradlew downloadApolloSchema \
  --endpoint="http://localhost:9090/graphql" \
  --schema="app/src/main/graphql/schema.json" \
  --header="Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MjMwNDg1MDksImV4cCI6MTYyMzA1NTcwOSwiaWRBbHVtbm8iOiIxNTc1YzY3Zi1lMjQ4LTQ2YmItOGNjNy03NDgyNzhmMzNiNmEiLCJjb3JyZW8iOiJzbWFkQGdtYWlsLmNvbSAgICAgICAgICAgICAgICAgICAgICIsIm5vbWJyZSI6IkNhcmxvcyBTZWJhc3RpYW4gTWFkcmlnYWwgUm9kcmlndWV6Iiwibm9Db250cm9sIjoiMTgxMjE2OTkgICJ9.wEQDcdypcre3m3apPoun2SYLAzhgwXksQEekqDaCQtwb-bLF2-FfkgxlEt65LTHENwTry4oK_ET_k3hiyyUkmQ"
